In [2]:
import numpy as np

## **Basics**

In [3]:
a = np.array([[1,2,3, 4, 5],[3,4,5,6, 7]])
print(a)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [4]:
# dimension
a.ndim

2

In [5]:
a.shape

(2, 5)

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.nbytes

80

## **Accessing and Changing Elements, Rows, Columns**

In [9]:
# Get a specific element (elements strt also at 0)
# [start_index : end_index]
a[1, 2]

5

In [10]:
# Negative can be used to access elements from the reversed order
a[1, -1]

7

In [11]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5])

In [12]:
# Get a specific column
a[:, 2]

array([3, 5])

In [13]:
# Get more elements at once
a[0, 1:4]

array([2, 3, 4])

In [14]:
# Replace
a[:,2] = [8,9]
print(a)

[[1 2 8 4 5]
 [3 4 9 6 7]]


### 3-d Array

In [15]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific elements
b[1,1,:]

array([7, 8])

In [17]:
b[1,1,1]

8

In [18]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## **Initializing Different Arrays**

In [19]:
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [22]:
# All 1s matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [26]:
# Reuse an array again
np.full_like(a.shape, 100)

array([100, 100])

In [27]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.16756002, 0.3454753 ],
       [0.38361128, 0.06949249],
       [0.40723936, 0.76831292],
       [0.30531509, 0.79895096]])

In [28]:
np.random.random_sample((4,3))

array([[0.54978104, 0.13278726, 0.325057  ],
       [0.6773389 , 0.24118644, 0.34523659],
       [0.93480897, 0.51201596, 0.07274313],
       [0.29119718, 0.18757001, 0.78664556]])

In [29]:
# Random integer numbers
np.random.randint(-4,7, size = (3,3))

array([[-4, -4,  4],
       [ 4,  3, -4],
       [ 6, -3,  5]])

In [30]:
# The identity matrix is a square
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#  Repeat an 1-d array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [32]:
arr = np.array([[1,2,3]]) # 2-d array
r2 = np.repeat(arr,3, axis = 0) # the axis defines this behaviour
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## **Initialize Array Problem**

In [33]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## **Copying Arrays Warning**

Be careful when copying arrays!!!

In [35]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 100

In [36]:
print(b)
print(a)

[  1   2 100   4   5]
[  1   2 100   4   5]


In [37]:
# Solution is to copy the content by .copy() and not just = because = refers memory location to the other item
a = np.array([1, 2, 3, 4, 5])
b = a.copy()
b[2] = 100

In [38]:
print(b)
print(a)

[  1   2 100   4   5]
[1 2 3 4 5]


## **Reorganizing Arrays**

In [41]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [43]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
# Vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# You can use more than one v here
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [59]:
# Horizontal stacking
h1 = np.zeros((4,4))
h2 = np.ones((4,4))

print(h1)
print()
print(h2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
np.hstack([h1,h2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

## **Boolean Masking (Advanced Indexing)**

In [78]:
data = np.array([29,97,32,100,45,15,88,5,75,22,44,77])

In [64]:
# Boolean Masking (Advanced Indexing)
data[data < 50]

array([29, 32, 45, 15,  5, 22])

In [65]:
np.any(data < 50)

True

In [66]:
np.all(data < 50)

False

## **Practice**

In [79]:
a = data.reshape((3,4))
a

array([[ 29,  97,  32, 100],
       [ 45,  15,  88,   5],
       [ 75,  22,  44,  77]])

In [80]:
a[1:2, 0:2] # getting a straight line slice

array([[45, 15]])

In [82]:
a[[0,1,2],[0,1,2,]] # getting a vertical line slice

array([29, 15, 44])